{% set version = "5.2.0" %}

package:
  name: nuget
  version: {{ version }}

source:
  url: https://dist.nuget.org/win-x86-commandline/v{{ version }}/nuget.exe
  sha256: 2865714c6588ef0770b4a04bdd20dac59bcb56756d001c040664c9966f1b835a

build:
  skip: True  # [not win]
  script: COPY nuget.exe %LIBRARY_BIN%\nuget.exe
  missing_dso_whitelist:
    - "*/mscoree.dll"

test:
  commands:
    - nuget help

about:
  home: https://www.nuget.org/
  license: MIT
  license_family: MIT
  # none available.  License is mentioned only in https://docs.microsoft.com/en-us/nuget/faqs/nuget-faq 
  # license_file: LICENSE.txt
  summary: .NET package manager

extra:
  recipe-maintainers:
    - msarahan


