package:
  name: apr
  version: 1.5.2

build:
  number:  1  [win]
  features:
    - vc9     [win and py27]
    - vc10    [win and py34]
    - vc14    [win and py35]

requirements:
  build:
    - python  [win]
    - curl
    - 7za     [win]

about:
  home: http://apr.apache.org/
  license: Apache License 2.0
  license_family: Apache
  summary: Maintains a consistent API with predictable behaviour
  description: |
    Apache Portable Runtime (APR) maintains software libraries
    that provides a consistent interface regardless of the platform on which
    software is built.
  doc_url: https://apr.apache.org/docs/apr/1.5/index.html
