package:
  name: svn
  version: 1.9.3

source:
  fn: subversion-1.9.3.tar.bz2
  url: http://www.trieuvan.com/apache/subversion/subversion-1.9.3.tar.bz2
  sha1: 27e8df191c92095f48314a415194ec37c682cbcf
  patches:
    - py3_compat.patch        [py>30]

build:
  features:
    - vc9     [win and py27]
    - vc10    [win and py34]
    - vc14    [win and py35]

requirements:
  build:
    - apr
    - openssl
    - python
    - sqlite
    - serf
    - swig
    - zlib
  run:
    - apr
    - openssl
    # python is here for getting correct vc feature only.  Not an actual dependency.
    - python   [win]
    - serf
    - sqlite
    - zlib

#test:
#  commands:
#    - svn help

about:
  home: https://subversion.apache.org/
  license: Apache Software License V.2
  license_family: Apache
  license_file: LICENSE
  summary: Enterprise-class centralized version control for the masses
  description: |
    Subversion is an open source, centralized version control system.
  doc_url: https://subversion.apache.org/docs/
